### ISSUE TITLE
Use rust stable instead of nightly-2020-11-09 ?

### ISSUE THREAD

**Issue by twitchyliquid64** [signalapp/libsignal-client#141]
Heya,

Looks like this builds fine on stable, is there a non-historical reason its pinned to nightly?

Or is it more of a 'we've verified some crypto generates without timing side channels on X version' kinda thing?

Cheers!
Tom

**Comment by jrose-signal** [comment]
It builds on stable for x86, but not for aarch64, due to the use of [intrinsics](https://en.wikipedia.org/wiki/Intrinsic_function) in the AES-GCM-SIV part. Additionally, [cbindgen](https://github.com/eqrion/cbindgen)'s support for macros requires nightly as well due to the use of unstable rustc flag `--pretty=expanded`. Rather than test against two different configurations, we decided to stick with nightly for now.

**Comment by twitchyliquid64** [comment]
Sounds good, thanks for the explanation!

**Comment by jrose-signal** [comment]
Pinning this issue for FAQ purposes! We do now test the Rust crates against stable in CI, but still use nightly as the canonical compiler for several reasons:
1. All our Rust -> $LANG interface generation relies on the unstable rustc flag `-Zunpretty=expanded`, either directly or through [cbindgen](https://github.com/eqrion/cbindgen).
2. The Mac Catalyst build for the Swift package depends on the unstable Cargo flag `-Zbuild-std`. (There is no Catalyst version of Signal at this time, but we want to keep the option open.)
3. We want to make sure we're using armv8 intrinsics where relevant for our cryptographic operations. (It's possible these have all been added to stable by now! But because of the other reasons there's no urgency to check.)

I believe everything else that depends on unstable flags is minor, and that that's all that's "keeping" us from stable. But (1) and (2) aren't likely to change any time soon.

**Comment by flynnshane32-jpg** [comment]
1. 

- [ ] #625

**Comment by djugei** [comment]
for further context, the tracking issues are:
[-Zunpretty=expanded](https://github.com/rust-lang/rust/issues/43364) and [-Zbuild-std](https://github.com/rust-lang/wg-cargo-std-aware)

both are, at the time of writing, not stabilized. the build script uses the nightly on stable hack though so i am unsure if this issue is still up to date.

**Comment by jrose-signal** [comment]
Years later, libsignal now builds with stable Rust after replacing cbindgen with manual interface generation based on collected metadata!

**Comment by twitchyliquid64** [comment]
We luv to see it!!! <3
