### ISSUE TITLE
WASM Bridge / Build for libsignal-client

### ISSUE THREAD

**Issue by ThisIsMissEm** [signalapp/libsignal-client#350]
Hi! It's really great to see libsignal has been rewritten in Rust, and this opens up an interesting possibility: libsignal-client bindings for the web via [wasm](https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm)

Given a few days looking through the codebase, I think it should be possible to get libsignal-client compiling to wasm, but unfortunately my rust knowledge is barely there, and I don't really understand the structure of all the macros used in this codebase.

I've pushed some early work on this [here](https://github.com/signalapp/libsignal-client/compare/master...unobvious-technology:wasm-bridge), but I'm having difficulty getting `bridge_fn` and similar macros working (I think I mostly lack information as to how to debug macros and see the code that they'd generate).

Is delivering libsignal-client via WASM of interest to Signal?

https://github.com/signalapp/libsignal-client/compare/master...unobvious-technology:wasm-bridge

**Comment by jrose-signal** [comment]
Our policy still matches what's in the README: _Contributions that will not be used directly by one of Signal's official client apps may still be considered, but only if they do not pose an undue maintenance burden or conflict with the goals of the project._ This is at least partly an issue of developer bandwidth at Signal! I think supporting a full wasm bridge would qualify as too much of a maintenance burden to land in the main repository.

That said, we're happy to take contributions that make it *easier* to use libsignal-client with other codebases, including some sort of wasm bridge.

* * *

Using libsignal-client from wasm apps could mean a few things:

1. Making sure the main libsignal-protocol crate compiles successfully for a wasm target, then using it from other Rust code that you also compile to wasm. This is easiest (it probably nearly works already) but it doesn't sound like that's your goal here.

2. Writing a manual wasm-friendly Rust wrapper library for the operations you care about, depending again on libsignal-protocol rather than libsignal-bridge. Basically the same as the previous one, except instead of making the entire app in Rust you're only making a library.

3. Using`#[bridge_fn]`* to autogenerate an API for wasm the same way we do for the three existing platforms. This has the obvious benefit that new bridged API will just appear when you update, but as you've seen there's an awful lot to `#[bridge_fn]`. [`cargo-expand`](https://github.com/dtolnay/cargo-expand) is the tool you're looking for to expand macros, though.

4. Using the existing *C* API (libsignal-ffi) as a clunky wasm-compatible interface. I'm not *really* sure I recommend this because we don't treat the C API as a product, just a means to an end for the Swift API, and so there's been no effort put into making it a proper friendly abstraction. But it's there and depending on your goals it could be useful.

"Depending on your goals" is really an operative phrase here. (2) is probably the target I'd suggest aiming for, since it means you get control over how libsignal-client's operations are translated to wasm, and that becomes insulation from changes to some extent. `#[bridge_fn]` may have been designed to be generic over multiple language bridges, but it's also not API in any sense, and as an implementation detail a change on our end could easily knock down an entire external house of cards.

Since we're not planning to make large changes directly in the main repo at this time, I'm going to close this issue, but please feel free to ask further questions at https://community.signalusers.org/c/development/6 (and tag me in your post to make sure I see it).

\* a towering abstraction that I really need to break back down into something approachable, but that's a separate issue!

**Comment by ThisIsMissEm** [comment]
Okay, so, I think I'm actually making forwards progress on this, as the rustwasm / wasm_bindgen projects can mostly automatically generate things correctly, there's just a little marshalling with serdes needed, I think.

For example, I've already managed to get it generating this:
<img width="798" alt="Screen Shot 2021-09-01 at 11 49 48 pm" src="https://user-images.githubusercontent.com/30827/131749940-9b8db0d5-2e30-4f0d-85a5-2c12275f96e6.png">

I guess I could manually create a wrapper package, but if it's minimal code to actually support wasm as a target within the core, then I'd likely be happy to maintain that aspect of the project? (My goal is to use libsignal as an underlying messaging layer for an application my company is developing)

**Comment by jrose-signal** [comment]
I appreciate the offer! But we're not really taking maintainers outside of Signal at this time, and we wouldn't, for example, want a feature for Signal's official clients blocked because it isn't building for wasm. You *could* do this by maintaining a downstream fork, though, like the Whisperfish project did before they got their work upstreamed. Then you deal with new features and changes on your schedule.

**Comment by zehrasaadet** [comment]
Hi @ThisIsMissEm With this work, did you able to achieve your goal? a working web project that uses signal web assembly?

**Comment by ThisIsMissEm** [comment]
Nope, I ended up abandoning the project

**Comment by zehrasaadet** [comment]
Is it because it is technically not possible ?  We're at the same point as you were 3 years ago. we have a goal to use signal on our web messaging platform. Is it possible for you to share some recommendations?

**Comment by ThisIsMissEm** [comment]
Nah, I was operating as a startup, and decided I needed to focus my resources on other efforts — bringing libsignal to wasm wasn't something I could do by myself at the time

**Comment by zehrasaadet** [comment]
Understand @ThisIsMissEm Many thanks for your rapid response 🙏🏻 🌸

**Comment by jrose-signal** [comment]
I'll note that approaches (3) and (4) I gave back in 2021 are much more difficult now that we have `boring` as a dependency, and possibly other C libraries in the indirect dependency tree that won't just accept a wasm target. (1) and (2) are still plausible. (And <https://community.signalusers.org/c/development/6> is still a better place for general discussion, though I realize in this case you were trying to reach ThisIsMissEm specifically!)

**Comment by zehrasaadet** [comment]
Hi Jordan @jrose-signal,   

Many thanks for your comments. 

Our goal is to use signal on a web based messaging platform in an e2e encrypted and multi device architecture.

we think that we need to do below 2 steps;

1- implement a bridge for wasm in signal rust code, and convert signal rust code to web assembly.
2- as we understand we also need a wrapper code. (As in java, swift and node.js). Browserify node.js javascript code and use it as a wrapper code.

Do you think it is correct?

I checked the signal community but there’s no technical  recommendation about how to use signal on web by converting  rust code to  web assembly.

**Comment by zehrasaadet** [comment]
Hi Jordan @jrose-signal 

In Signal, is there an official support who can provide technical consultancy? we need to use signal from web.
